### PR TITLE
Added custom partitionizer for subscribers/sinks

### PR DESCRIPTION
**Pull request by dbuschman7**
Added a param to pass in a function to derive the partition key for the message on the Kafka Topic. We do not use random partitioning.

### CODE REVIEW

**Comment by kciesielski** [comment]
Looks good. Could you addtionally format long argument lists (for `KafkaActorSubscriber` and `ReactiveKafka.publish()`) like here: http://docs.scala-lang.org/style/declarations.html ?

**Comment by dbuschman7** [comment]
I have made the requested changes, long argument lists and the toString nit. We use a sbt plugin called Scalaiform here to format the code when it compiles, I will add a PR that includes a basic one that you could start using here to insure all the code is formatted correctly. IT saves us much time in our PRs

**Comment by kciesielski** [comment]
Scalariform sounds like a good idea. Thank you for this update, merging now :)

**Comment by dbuschman7** [comment]
Looks like you did not merge the changes before you closed the PR

**Comment by kciesielski** [comment]
Of course. Merged now :)

**Pull request merged**
