### PR TITLE
Fix for issue #11 onNext IllegalStateException

### PR DESCRIPTION
**Pull request by dbuschman7**
We ran into the same problem and fixed the KafkaActorPublisher to handle this scenario. We see this when topics are new and contain no messages yet.

### CODE REVIEW

**Comment by kciesielski** [comment]
LGTM, thanks!

**Comment by dbuschman7** [comment]
Looks like you did not merge the changes before you closed the PR

**Comment by kciesielski** [comment]
Of course. Merged now :)

**Comment by thiagoandrade6** [comment]
Is that already published on maven?

**Comment by kciesielski** [comment]
@thiagoandrade6 Not yet. I want to review #14 and include it in the next release. It will be finished soon.

**Comment by thiagoandrade6** [comment]
ok, Thanks... for now I'm using the following code.

implicit val materializer =
    ActorFlowMaterializer(
      ActorFlowMaterializerSettings(actorSystem)
        .withInputBuffer(initialSize = 1024, maxSize = 1024))

**Pull request merged**
